### ISSUE TITLE
Misleading note at the bottom of webpage

### ISSUE THREAD

**Issue by jethomson** [lvgl/lv_font_conv#117]
"To use the Fonts without LVGL you need lv_font.c/h, lv_font_fmt_txt.c/h from [here](https://github.com/lvgl/lvgl/blob/master/src/misc)."

Is this note still true? Those files depend on several other files, so it seems misleading to wrong to say only those files are required.

Is there a collection of files that can be inserted into a project to use a converted font without using all of LVGL?

I was able to use fonts converted using the 5.3 version of the converter using a couple of extra files, but that converter has been taken down.

I would really appreciate it if it was possible to use fonts created by the new converter without including all of LVGL.

**Comment by jethomson** [comment]
I worked out a solution for myself which I have shared at the URL below.
An minimal set of files that are officially part of the LVGL project would be welcomed.
https://github.com/jethomson/lvgl_font_minimal

**Comment by kisvegabor** [comment]
Hi,

That statement was really outdated. Since than the font system of LVGL became more sophisticated and I believe using the converted fonts without LVGL would be quite complicated. Even if we could make it work, there is no guarantee that it will work in the future too. 

I'm sorry for saying that but there no intention to making this tool generic.  🙁
